### ISSUE TITLE
Error after deploying

### ISSUE THREAD

**Issue by paitoncamp** [apioo/fusio-sample-cms#4] opened 2021-06-12 07:30 UTC
I got this error after deploying 

> Fatal error: Uncaught Error: Class 'PSX\Framework\Environment\WebServer\Engine' not found in D:\xampp\htdocs\fusio-sample-cms\public\index.php:26 Stack trace: #0 {main} thrown in D:\xampp\htdocs\fusio-sample-cms\public\index.php on line 26

what is going wrong?

**Comment by chriskapp** [comment] 2021-06-12 09:15
Hi, it sounds like you have not executed `composer install` to install all dependencies through the composer packagemanager.

**Comment by paitoncamp** [comment] 2021-06-12 09:24
I did that already. Is it possible that it has something related with the fusio framework version?

**Comment by chriskapp** [comment] 2021-06-12 09:28
Yes this could be also a reason, please try to remove the `composer.lock` file and then run `composer install` again, through this you will obtain the latest versions of the dependencies.

**Comment by chriskapp** [comment] 2021-06-12 10:11
FYI I have also just updated the `composer.lock` file so that we use the correct dependencies.

**Comment by paitoncamp** [comment] 2021-06-13 13:30
Its still doesn't work for me :(   but I try to move it to the latest fusio framework installed and working fine.

**Comment by chriskapp** [comment] 2021-07-14 20:12
I will close this issue since it looks like the issue is solved, otherwise please open another issue.

**Closed as completed by chriskapp** 2021-07-14 20:12 UTC
